//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Integracion.net.azurewebsites.integracionwebservice201912344 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://intec.edu.do")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCuentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealizarTransaccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DepositarMontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetirarMontoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarCajeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagarPrestamoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTodasTransaccionesDelDiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTodasTransaccionesRangoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Integracion.Properties.Settings.Default.Integracion_net_azurewebsites_integracionwebservice201912344_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertarClienteCompletedEventHandler InsertarClienteCompleted;
        
        /// <remarks/>
        public event ObtenerClienteCompletedEventHandler ObtenerClienteCompleted;
        
        /// <remarks/>
        public event InsertarCuentaCompletedEventHandler InsertarCuentaCompleted;
        
        /// <remarks/>
        public event ObtenerCuentasCompletedEventHandler ObtenerCuentasCompleted;
        
        /// <remarks/>
        public event ObtenerCuentaCompletedEventHandler ObtenerCuentaCompleted;
        
        /// <remarks/>
        public event RealizarTransaccionCompletedEventHandler RealizarTransaccionCompleted;
        
        /// <remarks/>
        public event DepositarMontoCompletedEventHandler DepositarMontoCompleted;
        
        /// <remarks/>
        public event RetirarMontoCompletedEventHandler RetirarMontoCompleted;
        
        /// <remarks/>
        public event ValidarCajeroCompletedEventHandler ValidarCajeroCompleted;
        
        /// <remarks/>
        public event PagarPrestamoCompletedEventHandler PagarPrestamoCompleted;
        
        /// <remarks/>
        public event ObtenerTodasTransaccionesDelDiaCompletedEventHandler ObtenerTodasTransaccionesDelDiaCompleted;
        
        /// <remarks/>
        public event ObtenerTodasTransaccionesRangoCompletedEventHandler ObtenerTodasTransaccionesRangoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/InsertarCliente", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarCliente(Cliente cliente) {
            this.Invoke("InsertarCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(Cliente cliente) {
            this.InsertarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(Cliente cliente, object userState) {
            if ((this.InsertarClienteOperationCompleted == null)) {
                this.InsertarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarClienteOperationCompleted);
            }
            this.InvokeAsync("InsertarCliente", new object[] {
                        cliente}, this.InsertarClienteOperationCompleted, userState);
        }
        
        private void OnInsertarClienteOperationCompleted(object arg) {
            if ((this.InsertarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerCliente", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente ObtenerCliente(string nombre, string apellido) {
            object[] results = this.Invoke("ObtenerCliente", new object[] {
                        nombre,
                        apellido});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerClienteAsync(string nombre, string apellido) {
            this.ObtenerClienteAsync(nombre, apellido, null);
        }
        
        /// <remarks/>
        public void ObtenerClienteAsync(string nombre, string apellido, object userState) {
            if ((this.ObtenerClienteOperationCompleted == null)) {
                this.ObtenerClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerClienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerCliente", new object[] {
                        nombre,
                        apellido}, this.ObtenerClienteOperationCompleted, userState);
        }
        
        private void OnObtenerClienteOperationCompleted(object arg) {
            if ((this.ObtenerClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerClienteCompleted(this, new ObtenerClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/InsertarCuenta", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarCuenta(int numeroCuenta, string cedula, string nombres, string apellidos) {
            this.Invoke("InsertarCuenta", new object[] {
                        numeroCuenta,
                        cedula,
                        nombres,
                        apellidos});
        }
        
        /// <remarks/>
        public void InsertarCuentaAsync(int numeroCuenta, string cedula, string nombres, string apellidos) {
            this.InsertarCuentaAsync(numeroCuenta, cedula, nombres, apellidos, null);
        }
        
        /// <remarks/>
        public void InsertarCuentaAsync(int numeroCuenta, string cedula, string nombres, string apellidos, object userState) {
            if ((this.InsertarCuentaOperationCompleted == null)) {
                this.InsertarCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarCuentaOperationCompleted);
            }
            this.InvokeAsync("InsertarCuenta", new object[] {
                        numeroCuenta,
                        cedula,
                        nombres,
                        apellidos}, this.InsertarCuentaOperationCompleted, userState);
        }
        
        private void OnInsertarCuentaOperationCompleted(object arg) {
            if ((this.InsertarCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarCuentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerCuentas", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta[] ObtenerCuentas(string cedula) {
            object[] results = this.Invoke("ObtenerCuentas", new object[] {
                        cedula});
            return ((Cuenta[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCuentasAsync(string cedula) {
            this.ObtenerCuentasAsync(cedula, null);
        }
        
        /// <remarks/>
        public void ObtenerCuentasAsync(string cedula, object userState) {
            if ((this.ObtenerCuentasOperationCompleted == null)) {
                this.ObtenerCuentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCuentasOperationCompleted);
            }
            this.InvokeAsync("ObtenerCuentas", new object[] {
                        cedula}, this.ObtenerCuentasOperationCompleted, userState);
        }
        
        private void OnObtenerCuentasOperationCompleted(object arg) {
            if ((this.ObtenerCuentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCuentasCompleted(this, new ObtenerCuentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerCuenta", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta ObtenerCuenta(int numeroCuenta) {
            object[] results = this.Invoke("ObtenerCuenta", new object[] {
                        numeroCuenta});
            return ((Cuenta)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCuentaAsync(int numeroCuenta) {
            this.ObtenerCuentaAsync(numeroCuenta, null);
        }
        
        /// <remarks/>
        public void ObtenerCuentaAsync(int numeroCuenta, object userState) {
            if ((this.ObtenerCuentaOperationCompleted == null)) {
                this.ObtenerCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCuentaOperationCompleted);
            }
            this.InvokeAsync("ObtenerCuenta", new object[] {
                        numeroCuenta}, this.ObtenerCuentaOperationCompleted, userState);
        }
        
        private void OnObtenerCuentaOperationCompleted(object arg) {
            if ((this.ObtenerCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCuentaCompleted(this, new ObtenerCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/RealizarTransaccion", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RealizarTransaccion(int numeroCuentaRetiro, int numeroCuentaDeposito, decimal monto, TipoTransaccionesBancarias tipoTransaccion) {
            this.Invoke("RealizarTransaccion", new object[] {
                        numeroCuentaRetiro,
                        numeroCuentaDeposito,
                        monto,
                        tipoTransaccion});
        }
        
        /// <remarks/>
        public void RealizarTransaccionAsync(int numeroCuentaRetiro, int numeroCuentaDeposito, decimal monto, TipoTransaccionesBancarias tipoTransaccion) {
            this.RealizarTransaccionAsync(numeroCuentaRetiro, numeroCuentaDeposito, monto, tipoTransaccion, null);
        }
        
        /// <remarks/>
        public void RealizarTransaccionAsync(int numeroCuentaRetiro, int numeroCuentaDeposito, decimal monto, TipoTransaccionesBancarias tipoTransaccion, object userState) {
            if ((this.RealizarTransaccionOperationCompleted == null)) {
                this.RealizarTransaccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealizarTransaccionOperationCompleted);
            }
            this.InvokeAsync("RealizarTransaccion", new object[] {
                        numeroCuentaRetiro,
                        numeroCuentaDeposito,
                        monto,
                        tipoTransaccion}, this.RealizarTransaccionOperationCompleted, userState);
        }
        
        private void OnRealizarTransaccionOperationCompleted(object arg) {
            if ((this.RealizarTransaccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealizarTransaccionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/DepositarMonto", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta DepositarMonto(Cuenta cuenta, decimal monto) {
            object[] results = this.Invoke("DepositarMonto", new object[] {
                        cuenta,
                        monto});
            return ((Cuenta)(results[0]));
        }
        
        /// <remarks/>
        public void DepositarMontoAsync(Cuenta cuenta, decimal monto) {
            this.DepositarMontoAsync(cuenta, monto, null);
        }
        
        /// <remarks/>
        public void DepositarMontoAsync(Cuenta cuenta, decimal monto, object userState) {
            if ((this.DepositarMontoOperationCompleted == null)) {
                this.DepositarMontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDepositarMontoOperationCompleted);
            }
            this.InvokeAsync("DepositarMonto", new object[] {
                        cuenta,
                        monto}, this.DepositarMontoOperationCompleted, userState);
        }
        
        private void OnDepositarMontoOperationCompleted(object arg) {
            if ((this.DepositarMontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DepositarMontoCompleted(this, new DepositarMontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/RetirarMonto", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta RetirarMonto(Cuenta cuenta, decimal monto) {
            object[] results = this.Invoke("RetirarMonto", new object[] {
                        cuenta,
                        monto});
            return ((Cuenta)(results[0]));
        }
        
        /// <remarks/>
        public void RetirarMontoAsync(Cuenta cuenta, decimal monto) {
            this.RetirarMontoAsync(cuenta, monto, null);
        }
        
        /// <remarks/>
        public void RetirarMontoAsync(Cuenta cuenta, decimal monto, object userState) {
            if ((this.RetirarMontoOperationCompleted == null)) {
                this.RetirarMontoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetirarMontoOperationCompleted);
            }
            this.InvokeAsync("RetirarMonto", new object[] {
                        cuenta,
                        monto}, this.RetirarMontoOperationCompleted, userState);
        }
        
        private void OnRetirarMontoOperationCompleted(object arg) {
            if ((this.RetirarMontoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetirarMontoCompleted(this, new RetirarMontoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ValidarCajero", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cajero ValidarCajero(string usuario, string contraseña) {
            object[] results = this.Invoke("ValidarCajero", new object[] {
                        usuario,
                        contraseña});
            return ((Cajero)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarCajeroAsync(string usuario, string contraseña) {
            this.ValidarCajeroAsync(usuario, contraseña, null);
        }
        
        /// <remarks/>
        public void ValidarCajeroAsync(string usuario, string contraseña, object userState) {
            if ((this.ValidarCajeroOperationCompleted == null)) {
                this.ValidarCajeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarCajeroOperationCompleted);
            }
            this.InvokeAsync("ValidarCajero", new object[] {
                        usuario,
                        contraseña}, this.ValidarCajeroOperationCompleted, userState);
        }
        
        private void OnValidarCajeroOperationCompleted(object arg) {
            if ((this.ValidarCajeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarCajeroCompleted(this, new ValidarCajeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/PagarPrestamo", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta PagarPrestamo(Cuenta cuenta, Prestamo prestamo, decimal monto) {
            object[] results = this.Invoke("PagarPrestamo", new object[] {
                        cuenta,
                        prestamo,
                        monto});
            return ((Cuenta)(results[0]));
        }
        
        /// <remarks/>
        public void PagarPrestamoAsync(Cuenta cuenta, Prestamo prestamo, decimal monto) {
            this.PagarPrestamoAsync(cuenta, prestamo, monto, null);
        }
        
        /// <remarks/>
        public void PagarPrestamoAsync(Cuenta cuenta, Prestamo prestamo, decimal monto, object userState) {
            if ((this.PagarPrestamoOperationCompleted == null)) {
                this.PagarPrestamoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagarPrestamoOperationCompleted);
            }
            this.InvokeAsync("PagarPrestamo", new object[] {
                        cuenta,
                        prestamo,
                        monto}, this.PagarPrestamoOperationCompleted, userState);
        }
        
        private void OnPagarPrestamoOperationCompleted(object arg) {
            if ((this.PagarPrestamoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagarPrestamoCompleted(this, new PagarPrestamoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerTodasTransaccionesDelDia", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaccion[] ObtenerTodasTransaccionesDelDia(System.DateTime fecha) {
            object[] results = this.Invoke("ObtenerTodasTransaccionesDelDia", new object[] {
                        fecha});
            return ((Transaccion[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTodasTransaccionesDelDiaAsync(System.DateTime fecha) {
            this.ObtenerTodasTransaccionesDelDiaAsync(fecha, null);
        }
        
        /// <remarks/>
        public void ObtenerTodasTransaccionesDelDiaAsync(System.DateTime fecha, object userState) {
            if ((this.ObtenerTodasTransaccionesDelDiaOperationCompleted == null)) {
                this.ObtenerTodasTransaccionesDelDiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTodasTransaccionesDelDiaOperationCompleted);
            }
            this.InvokeAsync("ObtenerTodasTransaccionesDelDia", new object[] {
                        fecha}, this.ObtenerTodasTransaccionesDelDiaOperationCompleted, userState);
        }
        
        private void OnObtenerTodasTransaccionesDelDiaOperationCompleted(object arg) {
            if ((this.ObtenerTodasTransaccionesDelDiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTodasTransaccionesDelDiaCompleted(this, new ObtenerTodasTransaccionesDelDiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerTodasTransaccionesRango", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transaccion[] ObtenerTodasTransaccionesRango(System.DateTime fechaComienzo, System.DateTime fechaFinal) {
            object[] results = this.Invoke("ObtenerTodasTransaccionesRango", new object[] {
                        fechaComienzo,
                        fechaFinal});
            return ((Transaccion[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTodasTransaccionesRangoAsync(System.DateTime fechaComienzo, System.DateTime fechaFinal) {
            this.ObtenerTodasTransaccionesRangoAsync(fechaComienzo, fechaFinal, null);
        }
        
        /// <remarks/>
        public void ObtenerTodasTransaccionesRangoAsync(System.DateTime fechaComienzo, System.DateTime fechaFinal, object userState) {
            if ((this.ObtenerTodasTransaccionesRangoOperationCompleted == null)) {
                this.ObtenerTodasTransaccionesRangoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTodasTransaccionesRangoOperationCompleted);
            }
            this.InvokeAsync("ObtenerTodasTransaccionesRango", new object[] {
                        fechaComienzo,
                        fechaFinal}, this.ObtenerTodasTransaccionesRangoOperationCompleted, userState);
        }
        
        private void OnObtenerTodasTransaccionesRangoOperationCompleted(object arg) {
            if ((this.ObtenerTodasTransaccionesRangoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTodasTransaccionesRangoCompleted(this, new ObtenerTodasTransaccionesRangoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Cliente {
        
        private string matriculaField;
        
        private string nombresField;
        
        private string apellidosField;
        
        /// <remarks/>
        public string matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Cajero {
        
        private int idField;
        
        private string usuarioField;
        
        private string contraseñaField;
        
        private string nombresField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
        
        /// <remarks/>
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Transaccion {
        
        private int idField;
        
        private int numeroCuentaField;
        
        private string tipoTransaccionField;
        
        private decimal montoField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Prestamo {
        
        private int idField;
        
        private int numeroCuentaField;
        
        private decimal montoPendientePorPagarField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoPendientePorPagar {
            get {
                return this.montoPendientePorPagarField;
            }
            set {
                this.montoPendientePorPagarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Cuenta {
        
        private int numeroCuentaField;
        
        private string clienteCedulaField;
        
        private decimal balanceDisponibleField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private Prestamo[] prestamosField;
        
        private Transaccion[] transaccionesField;
        
        /// <remarks/>
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
        
        /// <remarks/>
        public string clienteCedula {
            get {
                return this.clienteCedulaField;
            }
            set {
                this.clienteCedulaField = value;
            }
        }
        
        /// <remarks/>
        public decimal balanceDisponible {
            get {
                return this.balanceDisponibleField;
            }
            set {
                this.balanceDisponibleField = value;
            }
        }
        
        /// <remarks/>
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public Prestamo[] prestamos {
            get {
                return this.prestamosField;
            }
            set {
                this.prestamosField = value;
            }
        }
        
        /// <remarks/>
        public Transaccion[] transacciones {
            get {
                return this.transaccionesField;
            }
            set {
                this.transaccionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public enum TipoTransaccionesBancarias {
        
        /// <remarks/>
        Interbancaria,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerClienteCompletedEventHandler(object sender, ObtenerClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertarCuentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerCuentasCompletedEventHandler(object sender, ObtenerCuentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCuentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCuentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerCuentaCompletedEventHandler(object sender, ObtenerCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RealizarTransaccionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DepositarMontoCompletedEventHandler(object sender, DepositarMontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DepositarMontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DepositarMontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RetirarMontoCompletedEventHandler(object sender, RetirarMontoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetirarMontoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetirarMontoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidarCajeroCompletedEventHandler(object sender, ValidarCajeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarCajeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarCajeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cajero Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cajero)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PagarPrestamoCompletedEventHandler(object sender, PagarPrestamoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagarPrestamoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PagarPrestamoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerTodasTransaccionesDelDiaCompletedEventHandler(object sender, ObtenerTodasTransaccionesDelDiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTodasTransaccionesDelDiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTodasTransaccionesDelDiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaccion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaccion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerTodasTransaccionesRangoCompletedEventHandler(object sender, ObtenerTodasTransaccionesRangoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTodasTransaccionesRangoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTodasTransaccionesRangoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transaccion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transaccion[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591