//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IntegracionWebService.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CoreServicesSoap", Namespace="http://intec.edu.do")]
    public partial class CoreServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActualizarCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarCajeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCajeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarPrestamoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActulizarPrestamoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerTodosPrestamosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CoreServices() {
            this.Url = global::IntegracionWebService.Properties.Settings.Default.IntegracionWebService_localhost_CoreServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActualizarCuentaCompletedEventHandler ActualizarCuentaCompleted;
        
        /// <remarks/>
        public event ObtenerCuentaCompletedEventHandler ObtenerCuentaCompleted;
        
        /// <remarks/>
        public event InsertarCajeroCompletedEventHandler InsertarCajeroCompleted;
        
        /// <remarks/>
        public event ObtenerCajeroCompletedEventHandler ObtenerCajeroCompleted;
        
        /// <remarks/>
        public event InsertarPrestamoCompletedEventHandler InsertarPrestamoCompleted;
        
        /// <remarks/>
        public event ActulizarPrestamoCompletedEventHandler ActulizarPrestamoCompleted;
        
        /// <remarks/>
        public event ObtenerTodosPrestamosCompletedEventHandler ObtenerTodosPrestamosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ActualizarCuenta", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarCuenta(int numeroCuenta, decimal montoPorAñadir, TipoTransaccion tipoTransaccion) {
            this.Invoke("ActualizarCuenta", new object[] {
                        numeroCuenta,
                        montoPorAñadir,
                        tipoTransaccion});
        }
        
        /// <remarks/>
        public void ActualizarCuentaAsync(int numeroCuenta, decimal montoPorAñadir, TipoTransaccion tipoTransaccion) {
            this.ActualizarCuentaAsync(numeroCuenta, montoPorAñadir, tipoTransaccion, null);
        }
        
        /// <remarks/>
        public void ActualizarCuentaAsync(int numeroCuenta, decimal montoPorAñadir, TipoTransaccion tipoTransaccion, object userState) {
            if ((this.ActualizarCuentaOperationCompleted == null)) {
                this.ActualizarCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarCuentaOperationCompleted);
            }
            this.InvokeAsync("ActualizarCuenta", new object[] {
                        numeroCuenta,
                        montoPorAñadir,
                        tipoTransaccion}, this.ActualizarCuentaOperationCompleted, userState);
        }
        
        private void OnActualizarCuentaOperationCompleted(object arg) {
            if ((this.ActualizarCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCuentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerCuenta", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta ObtenerCuenta(int numeroCuenta) {
            object[] results = this.Invoke("ObtenerCuenta", new object[] {
                        numeroCuenta});
            return ((Cuenta)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCuentaAsync(int numeroCuenta) {
            this.ObtenerCuentaAsync(numeroCuenta, null);
        }
        
        /// <remarks/>
        public void ObtenerCuentaAsync(int numeroCuenta, object userState) {
            if ((this.ObtenerCuentaOperationCompleted == null)) {
                this.ObtenerCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCuentaOperationCompleted);
            }
            this.InvokeAsync("ObtenerCuenta", new object[] {
                        numeroCuenta}, this.ObtenerCuentaOperationCompleted, userState);
        }
        
        private void OnObtenerCuentaOperationCompleted(object arg) {
            if ((this.ObtenerCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCuentaCompleted(this, new ObtenerCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/InsertarCajero", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarCajero(string nombres, string usuario, string contraseña) {
            this.Invoke("InsertarCajero", new object[] {
                        nombres,
                        usuario,
                        contraseña});
        }
        
        /// <remarks/>
        public void InsertarCajeroAsync(string nombres, string usuario, string contraseña) {
            this.InsertarCajeroAsync(nombres, usuario, contraseña, null);
        }
        
        /// <remarks/>
        public void InsertarCajeroAsync(string nombres, string usuario, string contraseña, object userState) {
            if ((this.InsertarCajeroOperationCompleted == null)) {
                this.InsertarCajeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarCajeroOperationCompleted);
            }
            this.InvokeAsync("InsertarCajero", new object[] {
                        nombres,
                        usuario,
                        contraseña}, this.InsertarCajeroOperationCompleted, userState);
        }
        
        private void OnInsertarCajeroOperationCompleted(object arg) {
            if ((this.InsertarCajeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarCajeroCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerCajero", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cajero ObtenerCajero(string usuario, string contraseña) {
            object[] results = this.Invoke("ObtenerCajero", new object[] {
                        usuario,
                        contraseña});
            return ((Cajero)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCajeroAsync(string usuario, string contraseña) {
            this.ObtenerCajeroAsync(usuario, contraseña, null);
        }
        
        /// <remarks/>
        public void ObtenerCajeroAsync(string usuario, string contraseña, object userState) {
            if ((this.ObtenerCajeroOperationCompleted == null)) {
                this.ObtenerCajeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCajeroOperationCompleted);
            }
            this.InvokeAsync("ObtenerCajero", new object[] {
                        usuario,
                        contraseña}, this.ObtenerCajeroOperationCompleted, userState);
        }
        
        private void OnObtenerCajeroOperationCompleted(object arg) {
            if ((this.ObtenerCajeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCajeroCompleted(this, new ObtenerCajeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/InsertarPrestamo", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarPrestamo(int numeroCuenta, decimal montoPrestamo) {
            this.Invoke("InsertarPrestamo", new object[] {
                        numeroCuenta,
                        montoPrestamo});
        }
        
        /// <remarks/>
        public void InsertarPrestamoAsync(int numeroCuenta, decimal montoPrestamo) {
            this.InsertarPrestamoAsync(numeroCuenta, montoPrestamo, null);
        }
        
        /// <remarks/>
        public void InsertarPrestamoAsync(int numeroCuenta, decimal montoPrestamo, object userState) {
            if ((this.InsertarPrestamoOperationCompleted == null)) {
                this.InsertarPrestamoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarPrestamoOperationCompleted);
            }
            this.InvokeAsync("InsertarPrestamo", new object[] {
                        numeroCuenta,
                        montoPrestamo}, this.InsertarPrestamoOperationCompleted, userState);
        }
        
        private void OnInsertarPrestamoOperationCompleted(object arg) {
            if ((this.InsertarPrestamoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarPrestamoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ActulizarPrestamo", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActulizarPrestamo(int idPrestamo, decimal cantidadPrestamo, decimal montoAPagar) {
            this.Invoke("ActulizarPrestamo", new object[] {
                        idPrestamo,
                        cantidadPrestamo,
                        montoAPagar});
        }
        
        /// <remarks/>
        public void ActulizarPrestamoAsync(int idPrestamo, decimal cantidadPrestamo, decimal montoAPagar) {
            this.ActulizarPrestamoAsync(idPrestamo, cantidadPrestamo, montoAPagar, null);
        }
        
        /// <remarks/>
        public void ActulizarPrestamoAsync(int idPrestamo, decimal cantidadPrestamo, decimal montoAPagar, object userState) {
            if ((this.ActulizarPrestamoOperationCompleted == null)) {
                this.ActulizarPrestamoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActulizarPrestamoOperationCompleted);
            }
            this.InvokeAsync("ActulizarPrestamo", new object[] {
                        idPrestamo,
                        cantidadPrestamo,
                        montoAPagar}, this.ActulizarPrestamoOperationCompleted, userState);
        }
        
        private void OnActulizarPrestamoOperationCompleted(object arg) {
            if ((this.ActulizarPrestamoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActulizarPrestamoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intec.edu.do/ObtenerTodosPrestamos", RequestNamespace="http://intec.edu.do", ResponseNamespace="http://intec.edu.do", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Prestamo[] ObtenerTodosPrestamos(int numeroCuenta) {
            object[] results = this.Invoke("ObtenerTodosPrestamos", new object[] {
                        numeroCuenta});
            return ((Prestamo[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerTodosPrestamosAsync(int numeroCuenta) {
            this.ObtenerTodosPrestamosAsync(numeroCuenta, null);
        }
        
        /// <remarks/>
        public void ObtenerTodosPrestamosAsync(int numeroCuenta, object userState) {
            if ((this.ObtenerTodosPrestamosOperationCompleted == null)) {
                this.ObtenerTodosPrestamosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerTodosPrestamosOperationCompleted);
            }
            this.InvokeAsync("ObtenerTodosPrestamos", new object[] {
                        numeroCuenta}, this.ObtenerTodosPrestamosOperationCompleted, userState);
        }
        
        private void OnObtenerTodosPrestamosOperationCompleted(object arg) {
            if ((this.ObtenerTodosPrestamosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerTodosPrestamosCompleted(this, new ObtenerTodosPrestamosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public enum TipoTransaccion {
        
        /// <remarks/>
        Deposito,
        
        /// <remarks/>
        Retiro,
        
        /// <remarks/>
        Transaccion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Cuenta {
        
        private int numeroCuentaField;
        
        private string clienteCedulaField;
        
        private decimal balanceDisponibleField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private Prestamo[] prestamosField;
        
        private Transaccion[] transaccionesField;
        
        /// <remarks/>
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
        
        /// <remarks/>
        public string clienteCedula {
            get {
                return this.clienteCedulaField;
            }
            set {
                this.clienteCedulaField = value;
            }
        }
        
        /// <remarks/>
        public decimal balanceDisponible {
            get {
                return this.balanceDisponibleField;
            }
            set {
                this.balanceDisponibleField = value;
            }
        }
        
        /// <remarks/>
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public Prestamo[] prestamos {
            get {
                return this.prestamosField;
            }
            set {
                this.prestamosField = value;
            }
        }
        
        /// <remarks/>
        public Transaccion[] transacciones {
            get {
                return this.transaccionesField;
            }
            set {
                this.transaccionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Prestamo {
        
        private int idField;
        
        private int numeroCuentaField;
        
        private decimal montoPendientePorPagarField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoPendientePorPagar {
            get {
                return this.montoPendientePorPagarField;
            }
            set {
                this.montoPendientePorPagarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Cajero {
        
        private int idField;
        
        private string usuarioField;
        
        private string contraseñaField;
        
        private string nombresField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
        
        /// <remarks/>
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intec.edu.do")]
    public partial class Transaccion {
        
        private int idField;
        
        private int numeroCuentaField;
        
        private string tipoTransaccionField;
        
        private decimal montoField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ActualizarCuentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerCuentaCompletedEventHandler(object sender, ObtenerCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertarCajeroCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerCajeroCompletedEventHandler(object sender, ObtenerCajeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCajeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCajeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cajero Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cajero)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertarPrestamoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ActulizarPrestamoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtenerTodosPrestamosCompletedEventHandler(object sender, ObtenerTodosPrestamosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerTodosPrestamosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerTodosPrestamosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Prestamo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Prestamo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591