//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracion.IntegracionReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int numeroCuentaField;
        
        private int clienteIdField;
        
        private decimal balanceDisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Integracion.IntegracionReference.Prestamo[] prestamosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                if ((this.numeroCuentaField.Equals(value) != true)) {
                    this.numeroCuentaField = value;
                    this.RaisePropertyChanged("numeroCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int clienteId {
            get {
                return this.clienteIdField;
            }
            set {
                if ((this.clienteIdField.Equals(value) != true)) {
                    this.clienteIdField = value;
                    this.RaisePropertyChanged("clienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal balanceDisponible {
            get {
                return this.balanceDisponibleField;
            }
            set {
                if ((this.balanceDisponibleField.Equals(value) != true)) {
                    this.balanceDisponibleField = value;
                    this.RaisePropertyChanged("balanceDisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Integracion.IntegracionReference.Prestamo[] prestamos {
            get {
                return this.prestamosField;
            }
            set {
                if ((object.ReferenceEquals(this.prestamosField, value) != true)) {
                    this.prestamosField = value;
                    this.RaisePropertyChanged("prestamos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prestamo", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Prestamo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int numeroCuentaField;
        
        private decimal montoPendientePorPagarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                if ((this.numeroCuentaField.Equals(value) != true)) {
                    this.numeroCuentaField = value;
                    this.RaisePropertyChanged("numeroCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal montoPendientePorPagar {
            get {
                return this.montoPendientePorPagarField;
            }
            set {
                if ((this.montoPendientePorPagarField.Equals(value) != true)) {
                    this.montoPendientePorPagarField = value;
                    this.RaisePropertyChanged("montoPendientePorPagar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTransaccion", Namespace="http://intec.edu.do")]
    public enum TipoTransaccion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interbancaria = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cajero", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Cajero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Transaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoTransaccionField;
        
        private System.DateTime fechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoTransaccionField, value) != true)) {
                    this.tipoTransaccionField = value;
                    this.RaisePropertyChanged("tipoTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do", ConfigurationName="IntegracionReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ObtenerCuentaResult from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/ObtenerCuenta", ReplyAction="*")]
        Integracion.IntegracionReference.ObtenerCuentaResponse ObtenerCuenta(Integracion.IntegracionReference.ObtenerCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/ObtenerCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.ObtenerCuentaResponse> ObtenerCuentaAsync(Integracion.IntegracionReference.ObtenerCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RealizarTransaccion", ReplyAction="*")]
        void RealizarTransaccion(int numeroCuentaRetiro, int numeroCuentaDeposito, decimal monto, Integracion.IntegracionReference.TipoTransaccion tipoTransaccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RealizarTransaccion", ReplyAction="*")]
        System.Threading.Tasks.Task RealizarTransaccionAsync(int numeroCuentaRetiro, int numeroCuentaDeposito, decimal monto, Integracion.IntegracionReference.TipoTransaccion tipoTransaccion);
        
        // CODEGEN: Generating message contract since element name cuenta from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DepositarMonto", ReplyAction="*")]
        Integracion.IntegracionReference.DepositarMontoResponse DepositarMonto(Integracion.IntegracionReference.DepositarMontoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DepositarMonto", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.DepositarMontoResponse> DepositarMontoAsync(Integracion.IntegracionReference.DepositarMontoRequest request);
        
        // CODEGEN: Generating message contract since element name cuenta from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RetirarMonto", ReplyAction="*")]
        Integracion.IntegracionReference.RetirarMontoResponse RetirarMonto(Integracion.IntegracionReference.RetirarMontoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RetirarMonto", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.RetirarMontoResponse> RetirarMontoAsync(Integracion.IntegracionReference.RetirarMontoRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/ValidarCajero", ReplyAction="*")]
        Integracion.IntegracionReference.ValidarCajeroResponse ValidarCajero(Integracion.IntegracionReference.ValidarCajeroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/ValidarCajero", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.ValidarCajeroResponse> ValidarCajeroAsync(Integracion.IntegracionReference.ValidarCajeroRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerTodasTransaccionesResult from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/ObtenerTodasTransacciones", ReplyAction="*")]
        Integracion.IntegracionReference.ObtenerTodasTransaccionesResponse ObtenerTodasTransacciones(Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/ObtenerTodasTransacciones", ReplyAction="*")]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.ObtenerTodasTransaccionesResponse> ObtenerTodasTransaccionesAsync(Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCuenta", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.ObtenerCuentaRequestBody Body;
        
        public ObtenerCuentaRequest() {
        }
        
        public ObtenerCuentaRequest(Integracion.IntegracionReference.ObtenerCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class ObtenerCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numeroCuenta;
        
        public ObtenerCuentaRequestBody() {
        }
        
        public ObtenerCuentaRequestBody(int numeroCuenta) {
            this.numeroCuenta = numeroCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCuentaResponse", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.ObtenerCuentaResponseBody Body;
        
        public ObtenerCuentaResponse() {
        }
        
        public ObtenerCuentaResponse(Integracion.IntegracionReference.ObtenerCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class ObtenerCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion.IntegracionReference.Cuenta ObtenerCuentaResult;
        
        public ObtenerCuentaResponseBody() {
        }
        
        public ObtenerCuentaResponseBody(Integracion.IntegracionReference.Cuenta ObtenerCuentaResult) {
            this.ObtenerCuentaResult = ObtenerCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositarMontoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositarMonto", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.DepositarMontoRequestBody Body;
        
        public DepositarMontoRequest() {
        }
        
        public DepositarMontoRequest(Integracion.IntegracionReference.DepositarMontoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DepositarMontoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion.IntegracionReference.Cuenta cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public DepositarMontoRequestBody() {
        }
        
        public DepositarMontoRequestBody(Integracion.IntegracionReference.Cuenta cuenta, decimal monto) {
            this.cuenta = cuenta;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepositarMontoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepositarMontoResponse", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.DepositarMontoResponseBody Body;
        
        public DepositarMontoResponse() {
        }
        
        public DepositarMontoResponse(Integracion.IntegracionReference.DepositarMontoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DepositarMontoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion.IntegracionReference.Cuenta DepositarMontoResult;
        
        public DepositarMontoResponseBody() {
        }
        
        public DepositarMontoResponseBody(Integracion.IntegracionReference.Cuenta DepositarMontoResult) {
            this.DepositarMontoResult = DepositarMontoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetirarMontoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetirarMonto", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.RetirarMontoRequestBody Body;
        
        public RetirarMontoRequest() {
        }
        
        public RetirarMontoRequest(Integracion.IntegracionReference.RetirarMontoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class RetirarMontoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion.IntegracionReference.Cuenta cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public RetirarMontoRequestBody() {
        }
        
        public RetirarMontoRequestBody(Integracion.IntegracionReference.Cuenta cuenta, decimal monto) {
            this.cuenta = cuenta;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetirarMontoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetirarMontoResponse", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.RetirarMontoResponseBody Body;
        
        public RetirarMontoResponse() {
        }
        
        public RetirarMontoResponse(Integracion.IntegracionReference.RetirarMontoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class RetirarMontoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion.IntegracionReference.Cuenta RetirarMontoResult;
        
        public RetirarMontoResponseBody() {
        }
        
        public RetirarMontoResponseBody(Integracion.IntegracionReference.Cuenta RetirarMontoResult) {
            this.RetirarMontoResult = RetirarMontoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCajeroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCajero", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.ValidarCajeroRequestBody Body;
        
        public ValidarCajeroRequest() {
        }
        
        public ValidarCajeroRequest(Integracion.IntegracionReference.ValidarCajeroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class ValidarCajeroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public ValidarCajeroRequestBody() {
        }
        
        public ValidarCajeroRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCajeroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCajeroResponse", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.ValidarCajeroResponseBody Body;
        
        public ValidarCajeroResponse() {
        }
        
        public ValidarCajeroResponse(Integracion.IntegracionReference.ValidarCajeroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class ValidarCajeroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion.IntegracionReference.Cajero ValidarCajeroResult;
        
        public ValidarCajeroResponseBody() {
        }
        
        public ValidarCajeroResponseBody(Integracion.IntegracionReference.Cajero ValidarCajeroResult) {
            this.ValidarCajeroResult = ValidarCajeroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodasTransaccionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodasTransacciones", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.ObtenerTodasTransaccionesRequestBody Body;
        
        public ObtenerTodasTransaccionesRequest() {
        }
        
        public ObtenerTodasTransaccionesRequest(Integracion.IntegracionReference.ObtenerTodasTransaccionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class ObtenerTodasTransaccionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numeroCuenta;
        
        public ObtenerTodasTransaccionesRequestBody() {
        }
        
        public ObtenerTodasTransaccionesRequestBody(int numeroCuenta) {
            this.numeroCuenta = numeroCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodasTransaccionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodasTransaccionesResponse", Namespace="http://intec.edu.do", Order=0)]
        public Integracion.IntegracionReference.ObtenerTodasTransaccionesResponseBody Body;
        
        public ObtenerTodasTransaccionesResponse() {
        }
        
        public ObtenerTodasTransaccionesResponse(Integracion.IntegracionReference.ObtenerTodasTransaccionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class ObtenerTodasTransaccionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Integracion.IntegracionReference.Transaccion[] ObtenerTodasTransaccionesResult;
        
        public ObtenerTodasTransaccionesResponseBody() {
        }
        
        public ObtenerTodasTransaccionesResponseBody(Integracion.IntegracionReference.Transaccion[] ObtenerTodasTransaccionesResult) {
            this.ObtenerTodasTransaccionesResult = ObtenerTodasTransaccionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Integracion.IntegracionReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Integracion.IntegracionReference.WebServiceSoap>, Integracion.IntegracionReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion.IntegracionReference.ObtenerCuentaResponse Integracion.IntegracionReference.WebServiceSoap.ObtenerCuenta(Integracion.IntegracionReference.ObtenerCuentaRequest request) {
            return base.Channel.ObtenerCuenta(request);
        }
        
        public Integracion.IntegracionReference.Cuenta ObtenerCuenta(int numeroCuenta) {
            Integracion.IntegracionReference.ObtenerCuentaRequest inValue = new Integracion.IntegracionReference.ObtenerCuentaRequest();
            inValue.Body = new Integracion.IntegracionReference.ObtenerCuentaRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            Integracion.IntegracionReference.ObtenerCuentaResponse retVal = ((Integracion.IntegracionReference.WebServiceSoap)(this)).ObtenerCuenta(inValue);
            return retVal.Body.ObtenerCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.ObtenerCuentaResponse> Integracion.IntegracionReference.WebServiceSoap.ObtenerCuentaAsync(Integracion.IntegracionReference.ObtenerCuentaRequest request) {
            return base.Channel.ObtenerCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion.IntegracionReference.ObtenerCuentaResponse> ObtenerCuentaAsync(int numeroCuenta) {
            Integracion.IntegracionReference.ObtenerCuentaRequest inValue = new Integracion.IntegracionReference.ObtenerCuentaRequest();
            inValue.Body = new Integracion.IntegracionReference.ObtenerCuentaRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            return ((Integracion.IntegracionReference.WebServiceSoap)(this)).ObtenerCuentaAsync(inValue);
        }
        
        public void RealizarTransaccion(int numeroCuentaRetiro, int numeroCuentaDeposito, decimal monto, Integracion.IntegracionReference.TipoTransaccion tipoTransaccion) {
            base.Channel.RealizarTransaccion(numeroCuentaRetiro, numeroCuentaDeposito, monto, tipoTransaccion);
        }
        
        public System.Threading.Tasks.Task RealizarTransaccionAsync(int numeroCuentaRetiro, int numeroCuentaDeposito, decimal monto, Integracion.IntegracionReference.TipoTransaccion tipoTransaccion) {
            return base.Channel.RealizarTransaccionAsync(numeroCuentaRetiro, numeroCuentaDeposito, monto, tipoTransaccion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion.IntegracionReference.DepositarMontoResponse Integracion.IntegracionReference.WebServiceSoap.DepositarMonto(Integracion.IntegracionReference.DepositarMontoRequest request) {
            return base.Channel.DepositarMonto(request);
        }
        
        public Integracion.IntegracionReference.Cuenta DepositarMonto(Integracion.IntegracionReference.Cuenta cuenta, decimal monto) {
            Integracion.IntegracionReference.DepositarMontoRequest inValue = new Integracion.IntegracionReference.DepositarMontoRequest();
            inValue.Body = new Integracion.IntegracionReference.DepositarMontoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.monto = monto;
            Integracion.IntegracionReference.DepositarMontoResponse retVal = ((Integracion.IntegracionReference.WebServiceSoap)(this)).DepositarMonto(inValue);
            return retVal.Body.DepositarMontoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.DepositarMontoResponse> Integracion.IntegracionReference.WebServiceSoap.DepositarMontoAsync(Integracion.IntegracionReference.DepositarMontoRequest request) {
            return base.Channel.DepositarMontoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion.IntegracionReference.DepositarMontoResponse> DepositarMontoAsync(Integracion.IntegracionReference.Cuenta cuenta, decimal monto) {
            Integracion.IntegracionReference.DepositarMontoRequest inValue = new Integracion.IntegracionReference.DepositarMontoRequest();
            inValue.Body = new Integracion.IntegracionReference.DepositarMontoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.monto = monto;
            return ((Integracion.IntegracionReference.WebServiceSoap)(this)).DepositarMontoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion.IntegracionReference.RetirarMontoResponse Integracion.IntegracionReference.WebServiceSoap.RetirarMonto(Integracion.IntegracionReference.RetirarMontoRequest request) {
            return base.Channel.RetirarMonto(request);
        }
        
        public Integracion.IntegracionReference.Cuenta RetirarMonto(Integracion.IntegracionReference.Cuenta cuenta, decimal monto) {
            Integracion.IntegracionReference.RetirarMontoRequest inValue = new Integracion.IntegracionReference.RetirarMontoRequest();
            inValue.Body = new Integracion.IntegracionReference.RetirarMontoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.monto = monto;
            Integracion.IntegracionReference.RetirarMontoResponse retVal = ((Integracion.IntegracionReference.WebServiceSoap)(this)).RetirarMonto(inValue);
            return retVal.Body.RetirarMontoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.RetirarMontoResponse> Integracion.IntegracionReference.WebServiceSoap.RetirarMontoAsync(Integracion.IntegracionReference.RetirarMontoRequest request) {
            return base.Channel.RetirarMontoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion.IntegracionReference.RetirarMontoResponse> RetirarMontoAsync(Integracion.IntegracionReference.Cuenta cuenta, decimal monto) {
            Integracion.IntegracionReference.RetirarMontoRequest inValue = new Integracion.IntegracionReference.RetirarMontoRequest();
            inValue.Body = new Integracion.IntegracionReference.RetirarMontoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.monto = monto;
            return ((Integracion.IntegracionReference.WebServiceSoap)(this)).RetirarMontoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion.IntegracionReference.ValidarCajeroResponse Integracion.IntegracionReference.WebServiceSoap.ValidarCajero(Integracion.IntegracionReference.ValidarCajeroRequest request) {
            return base.Channel.ValidarCajero(request);
        }
        
        public Integracion.IntegracionReference.Cajero ValidarCajero(string usuario, string contraseña) {
            Integracion.IntegracionReference.ValidarCajeroRequest inValue = new Integracion.IntegracionReference.ValidarCajeroRequest();
            inValue.Body = new Integracion.IntegracionReference.ValidarCajeroRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            Integracion.IntegracionReference.ValidarCajeroResponse retVal = ((Integracion.IntegracionReference.WebServiceSoap)(this)).ValidarCajero(inValue);
            return retVal.Body.ValidarCajeroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.ValidarCajeroResponse> Integracion.IntegracionReference.WebServiceSoap.ValidarCajeroAsync(Integracion.IntegracionReference.ValidarCajeroRequest request) {
            return base.Channel.ValidarCajeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion.IntegracionReference.ValidarCajeroResponse> ValidarCajeroAsync(string usuario, string contraseña) {
            Integracion.IntegracionReference.ValidarCajeroRequest inValue = new Integracion.IntegracionReference.ValidarCajeroRequest();
            inValue.Body = new Integracion.IntegracionReference.ValidarCajeroRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((Integracion.IntegracionReference.WebServiceSoap)(this)).ValidarCajeroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integracion.IntegracionReference.ObtenerTodasTransaccionesResponse Integracion.IntegracionReference.WebServiceSoap.ObtenerTodasTransacciones(Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest request) {
            return base.Channel.ObtenerTodasTransacciones(request);
        }
        
        public Integracion.IntegracionReference.Transaccion[] ObtenerTodasTransacciones(int numeroCuenta) {
            Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest inValue = new Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest();
            inValue.Body = new Integracion.IntegracionReference.ObtenerTodasTransaccionesRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            Integracion.IntegracionReference.ObtenerTodasTransaccionesResponse retVal = ((Integracion.IntegracionReference.WebServiceSoap)(this)).ObtenerTodasTransacciones(inValue);
            return retVal.Body.ObtenerTodasTransaccionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integracion.IntegracionReference.ObtenerTodasTransaccionesResponse> Integracion.IntegracionReference.WebServiceSoap.ObtenerTodasTransaccionesAsync(Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest request) {
            return base.Channel.ObtenerTodasTransaccionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integracion.IntegracionReference.ObtenerTodasTransaccionesResponse> ObtenerTodasTransaccionesAsync(int numeroCuenta) {
            Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest inValue = new Integracion.IntegracionReference.ObtenerTodasTransaccionesRequest();
            inValue.Body = new Integracion.IntegracionReference.ObtenerTodasTransaccionesRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            return ((Integracion.IntegracionReference.WebServiceSoap)(this)).ObtenerTodasTransaccionesAsync(inValue);
        }
    }
}
